/**
 * Responsive image utilities.
 *
 * Works with thumbnails generated by scripts/generate-thumbnails.mjs.
 * Generated files follow the pattern: `{name}-{width}w.{ext}`
 */

import responsiveImageManifest from '@/generated/responsive-image-manifest.json';

// ---------------------------------------------------------------------------
// Size presets matching the generation script
// ---------------------------------------------------------------------------

export type ImagePreset =
  | 'hero'
  | 'gallery'
  | 'packshot'
  | 'overview'
  | 'variants'
  | 'materials-full'
  | 'materials-thumb';

const PRESET_WIDTHS: Record<ImagePreset, number[]> = {
  hero: [640, 1280, 1920],
  gallery: [400, 800, 1200],
  packshot: [300, 600],
  overview: [400, 800],
  variants: [400, 800],
  'materials-full': [400, 800],
  'materials-thumb': [96, 192],
};

/**
 * Default `sizes` attribute hints per preset.
 * These are reasonable defaults – components can override.
 */
const PRESET_SIZES: Record<ImagePreset, string> = {
  hero: '100vw',
  gallery: '(min-width: 1024px) 33vw, 50vw',
  packshot: '(min-width: 1024px) 25vw, (min-width: 640px) 33vw, 50vw',
  overview: '(min-width: 1024px) 50vw, 100vw',
  variants: '(min-width: 1024px) 50vw, 100vw',
  'materials-full': '(min-width: 1024px) 50vw, 100vw',
  'materials-thumb': '96px',
};

const MANAGED_PUBLIC_PREFIXES = ['/catalogs/', '/shared/'] as const;
const GENERATED_WIDTHS_BY_SRC = responsiveImageManifest as Record<
  string,
  number[]
>;

function isManagedPublicAsset(src: string): boolean {
  return MANAGED_PUBLIC_PREFIXES.some((prefix) => src.startsWith(prefix));
}

function getGeneratedWidths(src: string): number[] | undefined {
  const widths = GENERATED_WIDTHS_BY_SRC[src];
  if (!Array.isArray(widths)) return undefined;

  return widths
    .filter((width): width is number => Number.isFinite(width) && width > 0)
    .sort((left, right) => left - right);
}

// ---------------------------------------------------------------------------
// srcset builder
// ---------------------------------------------------------------------------

function thumbnailUrl(src: string, width: number): string {
  const dotIndex = src.lastIndexOf('.');
  if (dotIndex === -1) return src;
  return `${src.slice(0, dotIndex)}-${width}w${src.slice(dotIndex)}`;
}

export interface ResponsiveImageProps {
  srcSet: string;
  sizes: string;
}

/**
 * Build `srcSet` and `sizes` attributes for a given image source and preset.
 *
 * @param src - The original image URL (e.g. `/catalogs/QX/hero/hero_00.webp`)
 * @param preset - The layout preset to use
 * @param sizesOverride - Optional custom `sizes` attribute
 * @returns Object with `srcSet` and `sizes` strings, or `undefined` if src is empty
 */
export function responsiveProps(
  src: string | undefined,
  preset: ImagePreset,
  sizesOverride?: string,
): ResponsiveImageProps | undefined {
  if (!src) return undefined;

  // Skip external URLs and SVGs
  if (src.startsWith('http') || src.endsWith('.svg')) return undefined;

  // Skip already-generated thumbnails
  if (/-\d+w\.\w+$/.test(src)) return undefined;

  const widths =
    getGeneratedWidths(src) ??
    (isManagedPublicAsset(src) ? [] : PRESET_WIDTHS[preset]);
  if (widths.length === 0) return undefined;

  const candidates = widths.map((w) => `${thumbnailUrl(src, w)} ${w}w`);
  // Always include the original as the largest candidate
  candidates.push(`${src} 4000w`);

  return {
    srcSet: candidates.join(', '),
    sizes: sizesOverride ?? PRESET_SIZES[preset],
  };
}

/**
 * Spread helper – returns props to spread onto an <img> element.
 *
 * Usage:
 *   <img src={src} {...responsiveImg(src, 'hero')} />
 */
export function responsiveImg(
  src: string | undefined,
  preset: ImagePreset,
  sizesOverride?: string,
): { srcSet?: string; sizes?: string } {
  const props = responsiveProps(src, preset, sizesOverride);
  if (!props) return {};
  return { srcSet: props.srcSet, sizes: props.sizes };
}
